services:
  e-banking-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  e-banking-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      e-banking-discovery-service:
        condition: service_healthy
  e-banking-account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-banking-config-service:
        condition: service_healthy
  e-banking-client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-banking-config-service:
        condition: service_healthy
  e-banking-transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-banking-config-service:
        condition: service_healthy
  e-banking-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - CONFIG_SERVICE_URL=http://config-service:9999
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      e-banking-config-service:
        condition: service_healthy
  front-end-angular:
    build: ./e-banking_app_ui
    container_name: front-end-angular
    ports:
      - '80:80'
    expose:
      - '80'